# Generated by Django 6.0.1 on 2026-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи (макс. 200 символов)', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст статьи', verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение для превью статьи', null=True, upload_to='blog/previews/', verbose_name='Превью (изображение)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, help_text='Опубликовать статью?', verbose_name='Признак публикации')),
                ('views_count', models.IntegerField(default=0, editable=False, verbose_name='Количество просмотров')),
                ('slug', models.SlugField(help_text='Уникальная часть URL для статьи (латинские буквы, цифры, дефисы)', max_length=200, unique=True, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Блоговая запись',
                'verbose_name_plural': 'Блоговые записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
